package main

// Test: HTTP-direct with valid PKCE (still fails at sign-in)
// Run: go run research/google-auth-flow/test_direct_oauth_valid_pkce.go

import (
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"
)

const (
	googleAuthURL = "https://accounts.google.com/o/oauth2/v2/auth"
	clientID      = "626581754197-v82pavblj7tgk6ap9ouqbi9lv821l6qo.apps.googleusercontent.com"
)

func pkce() (verifier, challenge string) {
	b := make([]byte, 32)
	for i := range b { b[i] = byte(i) }
	verifier = base64.RawURLEncoding.EncodeToString(b)
	sum := sha256.Sum256([]byte(verifier))
	challenge = base64.RawURLEncoding.EncodeToString(sum[:])
	return
}

func main() {
	verifier, challenge := pkce()

	authURL := googleAuthURL + "?" + url.Values{
		"client_id":             {clientID},
		"redirect_uri":          {"http://127.0.0.1:61120/callback"},
		"response_type":         {"code"},
		"scope":                 {"email profile openid"},
		"code_challenge":        {challenge},
		"code_challenge_method": {"S256"},
		"access_type":           {"offline"},
		"prompt":                {"select_account"},
	}.Encode()

	fmt.Println("=== STEP 1: Valid PKCE request ===")
	fmt.Printf("verifier:  %s\n", verifier)
	fmt.Printf("challenge: %s\n", challenge)
	fmt.Printf("GET %s\n\n", authURL)

	client := &http.Client{
		Timeout: 45 * time.Second,
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			fmt.Printf("  ↳ Redirect: %s %s\n", req.Method, req.URL.String())
			if len(via) >= 10 { return fmt.Errorf("too many redirects") }
			return nil
		},
	}

	req, _ := http.NewRequest(http.MethodGet, authURL, nil)
	req.Header.Set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36")
	req.Header.Set("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
	req.Header.Set("Accept-Language", "en-US,en;q=0.9")

	resp, err := client.Do(req)
	if err != nil {
		fmt.Printf("FAIL: %v\n", err)
		os.Exit(1)
	}
	defer resp.Body.Close()

	b, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	body := string(b)

	fmt.Printf("\nFinal URL: %s\n", resp.Request.URL.String())
	fmt.Printf("Status: %d\n", resp.StatusCode)
	fmt.Printf("Body length: %d bytes\n\n", len(body))

	fmt.Println("=== STEP 2: Analysis ===")

	if strings.Contains(resp.Request.URL.Path, "/signin/identifier") {
		fmt.Println("  → Got Google sign-in page (expected)")
	}
	if strings.Contains(resp.Request.URL.Path, "/signin/oauth/error") {
		fmt.Println("  → Got OAuth error page (unexpected)")
	}
	if strings.Contains(body, "gstatic.com") && strings.Contains(body, "script") {
		fmt.Println("  → Page loads JS from gstatic.com (browser required)")
	}
	if strings.Contains(body, "accounts.google.com") && strings.Contains(body, "dsh=") {
		fmt.Println("  → Contains dsh token in URLs (session-bound)")
	}

	fmt.Println("\n=== CONCLUSION ===")
	fmt.Println("Even with valid PKCE, Google redirects to a JS-heavy sign-in page.")
	fmt.Println("The sign-in form tokens are generated by JavaScript and are session-bound.")
	fmt.Println("HTTP-direct automation of the Google sign-in step is NOT possible.")
}
